# Generated by Django 6.0.5 on 2026-05-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BondOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investor_wallet", models.CharField(max_length=42)),
                ("issuer_wallet", models.CharField(max_length=42)),
                ("bond_symbol", models.CharField(default="BOND2027", max_length=32)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_per_bond",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=18),
                ),
                (
                    "stablecoin_symbol",
                    models.CharField(default="FAKEUR", max_length=16),
                ),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("settled", "Settled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
