# Generated by Django 6.0.5 on 2026-05-27 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("isin", models.CharField(blank=True, max_length=12)),
                ("issuer_name", models.CharField(max_length=120)),
                ("issuer_wallet", models.CharField(max_length=42)),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "coupon_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("maturity_date", models.DateField()),
                ("total_supply", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("wallet_address", models.CharField(max_length=42, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="bondorder",
            name="bond_symbol",
        ),
        migrations.RemoveField(
            model_name="bondorder",
            name="investor_wallet",
        ),
        migrations.RemoveField(
            model_name="bondorder",
            name="issuer_wallet",
        ),
        migrations.RemoveField(
            model_name="bondorder",
            name="transaction_hash",
        ),
        migrations.AlterField(
            model_name="bondorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("settlement_submitted", "Settlement submitted"),
                    ("settled", "Settled"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="bondorder",
            name="bond",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="settlements.bond",
            ),
        ),
        migrations.AddField(
            model_name="bondorder",
            name="investor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="settlements.investor",
            ),
        ),
        migrations.CreateModel(
            name="SettlementTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("local_ethereum", "Local Ethereum"),
                            ("ethereum", "Ethereum"),
                            ("tezos", "Tezos"),
                        ],
                        default="local_ethereum",
                        max_length=32,
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("block_number", models.PositiveBigIntegerField(blank=True, null=True)),
                ("gas_used", models.PositiveBigIntegerField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_transaction",
                        to="settlements.bondorder",
                    ),
                ),
            ],
        ),
    ]
