# Generated by Django 6.0.5 on 2026-05-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0002_bond_investor_remove_bondorder_bond_symbol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            (
                                "camt.054",
                                "camt.054 Bank to Customer Debit/Credit Notification",
                            )
                        ],
                        default="camt.054",
                        max_length=16,
                    ),
                ),
                ("message_id", models.CharField(max_length=64, unique=True)),
                ("xml_payload", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settlement_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_message",
                        to="settlements.settlementtransaction",
                    ),
                ),
            ],
        ),
    ]
